name: franchise-system
services:
  mysql:
    image: mysql:8.0
    container_name: franchise_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franchise_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - franchise_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - franchise_net
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:

networks:
  franchise_net:
    driver: bridge