name: Build, Test & SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CI + SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache de dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Dar permisos al wrapper de Maven
        run: chmod +x ./mvnw

      - name: Compilar, ejecutar pruebas y generar cobertura
        run: ./mvnw clean verify

      - name: Verificar que existe el reporte JaCoCo
        run: ls -la target/site/jacoco/

      - name: Análisis con SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=MariaVasquez_franchise_system
            -Dsonar.organization=mariavasquez
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}